refactor: change institution_status
MinhaCena/minha-cena-backend pull request #11
Opened 2023-03-03 02:13 UTC by maisalima01

2023-04-25 00:16 UTC, thaisminas requested changes

2023-04-25 00:16 UTC, thaisminas commented on prisma/schema.prisma
Teste

2023-05-08 21:42 UTC, thaisminas commented on src/infrastructure/database/mappers/prisma-illustrator-mapper.ts
> +  static toEntity(illustrator: PrismaIllustrator) {
@maisalima01 onde esse toEntity é usado?

2023-05-08 21:43 UTC, thaisminas commented on docker-compose.yml
> +  pgadmin:
@maisalima01 esse pgadmin é tipo o admin que eu tinha criado na imagem só que do postgres?

2023-05-08 21:52 UTC, thaisminas requested changes

2023-05-08 21:52 UTC, thaisminas commented on src/domain/entity/institution.ts
> +  institutionStatus: number;
@maisalima01 depois dá uma olhada se quebrou o endpoint de criar instituição se quebrou alguma coisa, visto que foi alterado a interface. Vamos sempre tentar confirmar os outros endpoint, e testes unitários quando tiver se quebrou alguma coisa na aplicação, para corrigirmos antes de mergearmos um PR.

2023-05-08 21:52 UTC, thaisminas commented on src/infrastructure/database/mappers/prisma-illustrator-mapper.ts
> +  static toEntity(illustrator: PrismaIllustrator) {
@maisalima01 onde esse toEntity é usado?

2023-05-08 21:52 UTC, thaisminas commented on docker-compose.yml
> +    container_name: pgadmin
@maisalima01 esse pgadmin é tipo o admin que eu tinha criado na imagem só que do postgres?

2023-05-08 22:14 UTC, maisalima01 commented on src/infrastructure/database/mappers/prisma-illustrator-mapper.ts
> +  static toEntity(illustrator: PrismaIllustrator) {
Thaís, ainda não está sendo utilizado.  Já criei essa parte para quando formos listar os ilustradores.

2023-05-08 22:14 UTC, maisalima01 commented on src/domain/entity/institution.ts
> +  institutionStatus: number;
Ok, Thaís. Irei testar.

2023-05-13 18:32 UTC, thaisminas approved these changes

2023-05-13 18:32 UTC, merged